### ISSUE TITLE
Add support for custom poll interval

### ISSUE THREAD

**Issue by emcepe** [hjdhjd/homebridge-hunter-hydrawise#1]
### Describe the feature request

please add an option to specify custom poll interval (like the other hydrawise plugin [https://github.com/martijndierckx/homebridge-hydrawise#readme](https://github.com/martijndierckx/homebridge-hydrawise#readme) does)

FYI:
you write:

> While the API provides the ability to suspend a zone, it does not provide the ability to resume a schedule.

one can resume a schedule (or all schedules): its like suspending but sending current time instead of future time.

### Describe the proposed solution

option "Polling interval" or something like that.

### Describe alternatives you have considered to the enhancement

Other hydrawise plugin (see above)

**Comment by emcepe** [comment]
don't know why github-actions bot closed this - Seems to be a silly AI bot ;-)

**Comment by emcepe** [comment]
@hjdhjd: please re-open this.

**Comment by hjdhjd** [comment]
> ### Describe the feature request
> please add an option to specify custom poll interval 

I am unlikely to implement this at this time. If you can provide a good use case for why this is useful, I'd welcome hearing about it, but aside from "I want to", I'm really only interested in adding features that an average person who wants things to "just work" would use.

So what's the useful use case?

> FYI: you write:
> 
> > While the API provides the ability to suspend a zone, it does not provide the ability to resume a schedule.
> 
> one can resume a schedule (or all schedules): its like suspending but sending current time instead of future time.
> 

Appreciate this insight. I'll take a closer look and see if that's in fact the case and its implications. Thanks for the heads up!

**Comment by emcepe** [comment]
> I am unlikely to implement this at this time. If you can provide a good use case for why this is useful, I'd welcome hearing about it, but aside from "I want to", I'm really only interested in adding features that an average person who wants things to "just work" would use.

I mainly use the Hydrawise FHEM Plugin and if I use your Homebridge plug-in too, then I get in trouble with the Hunter API limit which is very low (way too low if you ask me)
I am also not a friend of adding features just because of features but I think that's a good addition.

> Appreciate this insight. I'll take a closer look and see if that's in fact the case and its implications. Thanks for the heads up!

You're welcome. I use it that way with an enhanced Hydrawise FHEM Plugin, works w/o problems.

**Comment by hjdhjd** [comment]
What's the point in using both? At the end of the day, the whole reason to use Homebridge/HomeKit stuff is to enable as close to a realtime view of the state of a given accessory as possible. Reducing the update interval even further will reduce that visibility even further. My suggestion would be, especially given the API limitations, choose one thing and stick with it.
